server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2021-04-22T23:12:16.045+08:00[Asia/Shanghai] #https://docs.spring.io/spring-cloud-gateway/docs/3.0.3-SNAPSHOT/reference/html/#gateway-request-predicates-factories
            - Cookie=username,dtlalala

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka


